import type { Language, SynergyDefinition } from './types';

export const CHARACTER_COLOR_MAP: Record<string, string> = {
  red: 'ironclad',
  green: 'silent',
  blue: 'defect',
  purple: 'necrobinder',
  orange: 'regent',
};

export const SPIRE_CODEX_BASE_URL = 'https://spire-codex.com';
export const SPIRE_CODEX_API_URL = 'https://spire-codex.com/api';

export const LANG_MAP: Record<Language, string> = {
  en: 'eng',
  ko: 'kor',
};

export const CARD_TYPES = ['Attack', 'Skill', 'Power'] as const;

export const CARD_RARITIES = ['Basic', 'Common', 'Uncommon', 'Rare', 'Ancient'] as const;

// ── Synergy Definitions ─────────────────────────────────────────────────────

export const SYNERGY_DEFINITIONS: SynergyDefinition[] = [
  {
    id: 'poison',
    labelKey: 'synergy.poison',
    color: '#2ecc71',
    bgColor: 'rgba(46, 204, 113, 0.15)',
    borderColor: 'rgba(46, 204, 113, 0.4)',
    keywords: ['Poison'],
    descriptionPatterns: [/poison/i, /poisoned/i, /venomous/i, /독/, /중독/],
    varKeys: ['poison', 'poisonAmount'],
    tagPatterns: ['poison'],
  },
  {
    id: 'strength',
    labelKey: 'synergy.strength',
    color: '#e74c3c',
    bgColor: 'rgba(231, 76, 60, 0.15)',
    borderColor: 'rgba(231, 76, 60, 0.4)',
    keywords: ['Strength'],
    descriptionPatterns: [/strength/i, /gain \d+ strength/i, /힘/],
    varKeys: ['strength', 'strengthAmount'],
    tagPatterns: ['strength'],
  },
  {
    id: 'block',
    labelKey: 'synergy.block',
    color: '#3498db',
    bgColor: 'rgba(52, 152, 219, 0.15)',
    borderColor: 'rgba(52, 152, 219, 0.4)',
    keywords: ['Block'],
    descriptionPatterns: [/block/i, /armor/i, /shield/i, /방어/, /블록/],
    varKeys: ['block', 'blockAmount'],
    tagPatterns: ['block', 'defense'],
  },
  {
    id: 'draw',
    labelKey: 'synergy.draw',
    color: '#9b59b6',
    bgColor: 'rgba(155, 89, 182, 0.15)',
    borderColor: 'rgba(155, 89, 182, 0.4)',
    keywords: ['Draw'],
    descriptionPatterns: [/draw \d+ card/i, /draw a card/i, /뽑/, /드로/],
    varKeys: ['draw', 'drawAmount'],
    tagPatterns: ['draw'],
  },
  {
    id: 'exhaust',
    labelKey: 'synergy.exhaust',
    color: '#e67e22',
    bgColor: 'rgba(230, 126, 34, 0.15)',
    borderColor: 'rgba(230, 126, 34, 0.4)',
    keywords: ['Exhaust'],
    descriptionPatterns: [/exhaust/i, /exhausted/i, /소멸/],
    varKeys: [],
    tagPatterns: ['exhaust'],
  },
  {
    id: 'retain',
    labelKey: 'synergy.retain',
    color: '#1abc9c',
    bgColor: 'rgba(26, 188, 156, 0.15)',
    borderColor: 'rgba(26, 188, 156, 0.4)',
    keywords: ['Retain'],
    descriptionPatterns: [/retain/i, /보존/],
    varKeys: [],
    tagPatterns: ['retain'],
  },
  {
    id: 'innate',
    labelKey: 'synergy.innate',
    color: '#f39c12',
    bgColor: 'rgba(243, 156, 18, 0.15)',
    borderColor: 'rgba(243, 156, 18, 0.4)',
    keywords: ['Innate'],
    descriptionPatterns: [/innate/i, /선천/],
    varKeys: [],
    tagPatterns: ['innate'],
  },
  {
    id: 'ethereal',
    labelKey: 'synergy.ethereal',
    color: '#a29bfe',
    bgColor: 'rgba(162, 155, 254, 0.15)',
    borderColor: 'rgba(162, 155, 254, 0.4)',
    keywords: ['Ethereal'],
    descriptionPatterns: [/ethereal/i, /휘발/],
    varKeys: [],
    tagPatterns: ['ethereal'],
  },
  {
    id: 'energy',
    labelKey: 'synergy.energy',
    color: '#fdcb6e',
    bgColor: 'rgba(253, 203, 110, 0.15)',
    borderColor: 'rgba(253, 203, 110, 0.4)',
    keywords: ['Energy'],
    descriptionPatterns: [/gain \d+ energy/i, /\benergy\b/i],
    varKeys: ['energy', 'energyAmount'],
    tagPatterns: ['energy'],
  },
  {
    id: 'aoe',
    labelKey: 'synergy.aoe',
    color: '#fd79a8',
    bgColor: 'rgba(253, 121, 168, 0.15)',
    borderColor: 'rgba(253, 121, 168, 0.4)',
    keywords: [],
    descriptionPatterns: [/all enemies/i, /each enemy/i, /모든 적/, /적 전체/],
    varKeys: [],
    tagPatterns: ['aoe', 'multi_target'],
  },
  {
    id: 'scry',
    labelKey: 'synergy.scry',
    color: '#74b9ff',
    bgColor: 'rgba(116, 185, 255, 0.15)',
    borderColor: 'rgba(116, 185, 255, 0.4)',
    keywords: ['Scry'],
    descriptionPatterns: [/scry/i, /예지/],
    varKeys: ['scry', 'scryAmount'],
    tagPatterns: ['scry'],
  },
  {
    id: 'healing',
    labelKey: 'synergy.healing',
    color: '#55efc4',
    bgColor: 'rgba(85, 239, 196, 0.15)',
    borderColor: 'rgba(85, 239, 196, 0.4)',
    keywords: [],
    descriptionPatterns: [/heal \d+/i, /restore \d+ hp/i, /regain/i, /회복/, /치유/],
    varKeys: ['heal', 'healAmount'],
    tagPatterns: ['healing'],
  },
  // ── New synergies ───────────────────────────────────────────────────────────
  {
    id: 'vulnerable',
    labelKey: 'synergy.vulnerable',
    color: '#e17055',
    bgColor: 'rgba(225, 112, 85, 0.15)',
    borderColor: 'rgba(225, 112, 85, 0.4)',
    keywords: ['Vulnerable'],
    descriptionPatterns: [/vulnerable/i, /취약/],
    varKeys: [],
    tagPatterns: ['vulnerable'],
  },
  {
    id: 'weak',
    labelKey: 'synergy.weak',
    color: '#fdcb6e',
    bgColor: 'rgba(253, 203, 110, 0.15)',
    borderColor: 'rgba(253, 203, 110, 0.4)',
    keywords: ['Weak'],
    descriptionPatterns: [/weak/i, /약화/],
    varKeys: [],
    tagPatterns: ['weak'],
  },
  {
    id: 'dexterity',
    labelKey: 'synergy.dexterity',
    color: '#00b894',
    bgColor: 'rgba(0, 184, 148, 0.15)',
    borderColor: 'rgba(0, 184, 148, 0.4)',
    keywords: ['Dexterity'],
    descriptionPatterns: [/dexterity/i, /민첩/],
    varKeys: ['dexterity'],
    tagPatterns: ['dexterity'],
  },
  {
    id: 'intangible',
    labelKey: 'synergy.intangible',
    color: '#dfe6e9',
    bgColor: 'rgba(223, 230, 233, 0.15)',
    borderColor: 'rgba(223, 230, 233, 0.4)',
    keywords: ['Intangible'],
    descriptionPatterns: [/intangible/i, /불가침/],
    varKeys: [],
    tagPatterns: ['intangible'],
  },
  {
    id: 'focus',
    labelKey: 'synergy.focus',
    color: '#0984e3',
    bgColor: 'rgba(9, 132, 227, 0.15)',
    borderColor: 'rgba(9, 132, 227, 0.4)',
    keywords: ['Focus'],
    descriptionPatterns: [/focus/i, /집중/],
    varKeys: ['focus'],
    tagPatterns: ['focus'],
  },
  {
    id: 'orbs',
    labelKey: 'synergy.orbs',
    color: '#6c5ce7',
    bgColor: 'rgba(108, 92, 231, 0.15)',
    borderColor: 'rgba(108, 92, 231, 0.4)',
    keywords: [],
    descriptionPatterns: [/channel/i, /evoke/i, /orb/i, /lightning/i, /frost/i, /dark orb/i, /plasma/i, /채널/i, /발동/i],
    varKeys: [],
    tagPatterns: ['orb', 'channel', 'evoke'],
  },
  {
    id: 'summon',
    labelKey: 'synergy.summon',
    color: '#a29bfe',
    bgColor: 'rgba(162, 155, 254, 0.15)',
    borderColor: 'rgba(162, 155, 254, 0.4)',
    keywords: ['Summon'],
    descriptionPatterns: [/summon/i, /소환/],
    varKeys: ['Summon', 'summon'],
    tagPatterns: ['summon'],
  },
  {
    id: 'doom',
    labelKey: 'synergy.doom',
    color: '#2d3436',
    bgColor: 'rgba(45, 52, 54, 0.15)',
    borderColor: 'rgba(45, 52, 54, 0.4)',
    keywords: ['Doom'],
    descriptionPatterns: [/doom/i, /종말/],
    varKeys: [],
    tagPatterns: ['doom'],
  },
  {
    id: 'stars',
    labelKey: 'synergy.stars',
    color: '#ffeaa7',
    bgColor: 'rgba(255, 234, 167, 0.15)',
    borderColor: 'rgba(255, 234, 167, 0.4)',
    keywords: [],
    descriptionPatterns: [/star/i, /forge/i, /별/, /단조/],
    varKeys: [],
    tagPatterns: ['star', 'forge'],
  },
  {
    id: 'sly',
    labelKey: 'synergy.sly',
    color: '#00cec9',
    bgColor: 'rgba(0, 206, 201, 0.15)',
    borderColor: 'rgba(0, 206, 201, 0.4)',
    keywords: ['Sly'],
    descriptionPatterns: [/sly/i, /교활/],
    varKeys: [],
    tagPatterns: ['sly'],
  },
  {
    id: 'discard',
    labelKey: 'synergy.discard',
    color: '#636e72',
    bgColor: 'rgba(99, 110, 114, 0.15)',
    borderColor: 'rgba(99, 110, 114, 0.4)',
    keywords: [],
    descriptionPatterns: [/discard/i, /버리/],
    varKeys: [],
    tagPatterns: ['discard'],
  },
  {
    id: 'plating',
    labelKey: 'synergy.plating',
    color: '#b2bec3',
    bgColor: 'rgba(178, 190, 195, 0.15)',
    borderColor: 'rgba(178, 190, 195, 0.4)',
    keywords: ['Plating'],
    descriptionPatterns: [/plating/i, /도금/],
    varKeys: [],
    tagPatterns: ['plating'],
  },
  {
    id: 'vigor',
    labelKey: 'synergy.vigor',
    color: '#ff7675',
    bgColor: 'rgba(255, 118, 117, 0.15)',
    borderColor: 'rgba(255, 118, 117, 0.4)',
    keywords: ['Vigor'],
    descriptionPatterns: [/vigor/i, /활력/],
    varKeys: ['vigor'],
    tagPatterns: ['vigor'],
  },
];

export const UI_STRINGS: Record<Language, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.deckBuilder': 'Deck Builder',
    'nav.title': 'STS2 Deck Builder',

    'landing.hero.title': 'Build Your Perfect Deck',
    'landing.hero.subtitle': 'Create, save, and share decks for Slay the Spire 2',
    'landing.hero.cta': 'Start Building',

    'deck.save': 'Save Deck',
    'deck.share': 'Share Deck',
    'deck.clear': 'Clear Deck',
    'deck.load': 'Load Deck',
    'deck.delete': 'Delete Deck',
    'deck.name': 'Deck Name',
    'deck.unnamed': 'Unnamed Deck',
    'deck.loadDeck': 'Load Deck',
    'deck.noSavedDecks': 'No saved decks',
    'deck.cardCount': 'cards',
    'deck.deleteConfirm': 'Delete this deck?',
    'deck.importCode': 'Import Deck Code',
    'deck.importCodePlaceholder': 'Paste deck code here...',
    'deck.import': 'Import',
    'deck.invalidCode': 'Invalid deck code. Please check and try again.',
    'deck.savedDecks': 'Saved Decks',
    'deck.codeCopied': 'Deck code copied!',

    'deck.stats.total': 'Total Cards',
    'deck.stats.attacks': 'Attacks',
    'deck.stats.skills': 'Skills',
    'deck.stats.powers': 'Powers',
    'deck.stats.costCurve': 'Cost Curve',

    'filter.type': 'Type',
    'filter.rarity': 'Rarity',
    'filter.cost': 'Cost',
    'filter.keyword': 'Keyword',
    'filter.search': 'Search cards...',
    'filter.all': 'All',

    'char.select': 'Select Character',
    'char.hp': 'HP',
    'char.energy': 'Energy',

    'share.copied': 'Link copied to clipboard!',
    'share.title': 'Share Deck',

    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.close': 'Close',

    'relic.startingRelic': 'Starting Relic',
    'relic.relics': 'Relics',
    'relic.flavor': 'Flavor',
    'relic.browse': 'Browse Relics',
    'relic.added': 'Added Relics',
    'relic.characterPool': 'Character Relics',
    'relic.sharedPool': 'Shared Relics',
    'relic.empty': 'No relics added yet',
    'relic.add': 'Add relic',
    'relic.remove': 'Remove relic',
    'relic.search': 'Search relics...',

    'synergy.title': 'Synergies',
    'synergy.filter': 'Synergy',
    'synergy.poison': 'Poison',
    'synergy.strength': 'Strength',
    'synergy.block': 'Block',
    'synergy.draw': 'Draw',
    'synergy.exhaust': 'Exhaust',
    'synergy.retain': 'Retain',
    'synergy.innate': 'Innate',
    'synergy.ethereal': 'Ethereal',
    'synergy.energy': 'Energy',
    'synergy.aoe': 'AoE',
    'synergy.scry': 'Scry',
    'synergy.healing': 'Healing',
    'synergy.vulnerable': 'Vulnerable',
    'synergy.weak': 'Weak',
    'synergy.dexterity': 'Dexterity',
    'synergy.intangible': 'Intangible',
    'synergy.focus': 'Focus',
    'synergy.orbs': 'Orbs',
    'synergy.summon': 'Summon',
    'synergy.doom': 'Doom',
    'synergy.stars': 'Stars',
    'synergy.sly': 'Sly',
    'synergy.discard': 'Discard',
    'synergy.plating': 'Plating',
    'synergy.vigor': 'Vigor',
    'synergy.breakdown': 'Synergy Breakdown',
    'synergy.none': 'No synergies detected',

    'lang.en': 'English',
    'lang.ko': '한국어',
  },
  ko: {
    'nav.home': '홈',
    'nav.deckBuilder': '덱 빌더',
    'nav.title': 'STS2 덱 빌더',

    'landing.hero.title': '완벽한 덱을 만들어보세요',
    'landing.hero.subtitle': 'Slay the Spire 2를 위한 덱을 제작, 저장, 공유하세요',
    'landing.hero.cta': '빌딩 시작',

    'deck.save': '덱 저장',
    'deck.share': '덱 공유',
    'deck.clear': '덱 초기화',
    'deck.load': '덱 불러오기',
    'deck.delete': '덱 삭제',
    'deck.name': '덱 이름',
    'deck.unnamed': '이름 없는 덱',
    'deck.loadDeck': '덱 불러오기',
    'deck.noSavedDecks': '저장된 덱이 없습니다',
    'deck.cardCount': '장',
    'deck.deleteConfirm': '이 덱을 삭제하시겠습니까?',
    'deck.importCode': '덱 코드 가져오기',
    'deck.importCodePlaceholder': '덱 코드를 붙여넣으세요...',
    'deck.import': '가져오기',
    'deck.invalidCode': '잘못된 덱 코드입니다. 확인 후 다시 시도해 주세요.',
    'deck.savedDecks': '저장된 덱',
    'deck.codeCopied': '덱 코드 복사 완료!',

    'deck.stats.total': '총 카드 수',
    'deck.stats.attacks': '공격',
    'deck.stats.skills': '스킬',
    'deck.stats.powers': '파워',
    'deck.stats.costCurve': '코스트 곡선',

    'filter.type': '타입',
    'filter.rarity': '희귀도',
    'filter.cost': '코스트',
    'filter.keyword': '키워드',
    'filter.search': '카드 검색...',
    'filter.all': '전체',

    'char.select': '캐릭터 선택',
    'char.hp': 'HP',
    'char.energy': '에너지',

    'share.copied': '링크가 클립보드에 복사되었습니다!',
    'share.title': '덱 공유',

    'common.cancel': '취소',
    'common.confirm': '확인',
    'common.close': '닫기',

    'relic.startingRelic': '시작 유물',
    'relic.relics': '유물',
    'relic.flavor': '설명',
    'relic.browse': '유물 찾아보기',
    'relic.added': '추가된 유물',
    'relic.characterPool': '캐릭터 유물',
    'relic.sharedPool': '공유 유물',
    'relic.empty': '아직 추가된 유물이 없습니다',
    'relic.add': '유물 추가',
    'relic.remove': '유물 제거',
    'relic.search': '유물 검색...',

    'synergy.title': '시너지',
    'synergy.filter': '시너지',
    'synergy.poison': '독',
    'synergy.strength': '힘',
    'synergy.block': '방어',
    'synergy.draw': '드로우',
    'synergy.exhaust': '소멸',
    'synergy.retain': '보존',
    'synergy.innate': '선천',
    'synergy.ethereal': '에테르',
    'synergy.energy': '에너지',
    'synergy.aoe': '광역',
    'synergy.scry': '점술',
    'synergy.healing': '치유',
    'synergy.vulnerable': '취약',
    'synergy.weak': '약화',
    'synergy.dexterity': '민첩',
    'synergy.intangible': '불가침',
    'synergy.focus': '집중',
    'synergy.orbs': '오브',
    'synergy.summon': '소환',
    'synergy.doom': '종말',
    'synergy.stars': '별',
    'synergy.sly': '교활',
    'synergy.discard': '버리기',
    'synergy.plating': '도금',
    'synergy.vigor': '활력',
    'synergy.breakdown': '시너지 분석',
    'synergy.none': '감지된 시너지 없음',

    'lang.en': 'English',
    'lang.ko': '한국어',
  },
};
